#sudo: false
language: node_js
node_js:
  - '0.10'
before_script:
  - gem install compass
  - npm install
  - npm install bower
  - bower install
  - npm install grunt-cli
  - grunt
#  - 'npm install -g bower grunt-cli'
#  - 'bower install'
